### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'metavar'

### ISSUE THREAD

**Issue by caot** [nganvu/magic#77]
Just installed the most recent update, however it got the mentioned error. What might be the issue?

	$ MAGIC.py
	Traceback (most recent call last):
	  File "/opt/anaconda3/bin/MAGIC.py", line 120, in <module>
	    main(sys.argv[1:])
	  File "/opt/anaconda3/bin/MAGIC.py", line 82, in main
	    args = parse_args(args)
	  File "/opt/anaconda3/bin/MAGIC.py", line 69, in parse_args
	    help='Plot R2 plot generated in optimal t calculation (Default=False).')
	  File "/opt/anaconda3/lib/python3.6/argparse.py", line 1334, in add_argument
	    action = action_class(**kwargs)
	TypeError: __init__() got an unexpected keyword argument 'metavar'

	$ git log -n 1
	commit 044038e4b70a79af4950a63075c3aaeb51eea893
	Merge: 0929f2b 03bb376
	Author: Pooja Kathail <pk2485@columbia.edu>
	Date:   Fri Jan 26 17:19:52 2018 -0500

	    fix merge conflicts

**Comment by caot** [comment]
removed unexpected keyword argument 'metavar'
